// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UseQuery$ReScriptUrql from "./UseQuery.res.mjs";
import * as UseMutation$ReScriptUrql from "./UseMutation.res.mjs";
import * as UseSubscription$ReScriptUrql from "./UseSubscription.res.mjs";

var useQuery = UseQuery$ReScriptUrql.useQuery;

var useMutation = UseMutation$ReScriptUrql.useMutation;

var useSubscription = UseSubscription$ReScriptUrql.useSubscription;

export {
  useQuery ,
  useMutation ,
  useSubscription ,
}
/* UseQuery-ReScriptUrql Not a pure module */
