// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Urql from "urql";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Types$ReScriptUrql from "../Types.res.mjs";

function useSubscription(Subscription, handler, pause, additionalTypenames, fetchOptions, $$fetch, requestPolicy, url, meta, suspense, preferGetMethod, variables) {
  var query = Subscription.query;
  var parse = Subscription.parse;
  var rp = React.useMemo((function (param) {
          return Belt_Option.map(requestPolicy, Types$ReScriptUrql.requestPolicyToJs);
        }), [requestPolicy]);
  var context = React.useMemo((function (param) {
          var tmp = {};
          if (additionalTypenames !== undefined) {
            tmp.additionalTypenames = Caml_option.valFromOption(additionalTypenames);
          }
          if ($$fetch !== undefined) {
            tmp.fetch = Caml_option.valFromOption($$fetch);
          }
          if (fetchOptions !== undefined) {
            tmp.fetchOptions = Caml_option.valFromOption(fetchOptions);
          }
          if (rp !== undefined) {
            tmp.requestPolicy = Caml_option.valFromOption(rp);
          }
          if (url !== undefined) {
            tmp.url = Caml_option.valFromOption(url);
          }
          if (meta !== undefined) {
            tmp.meta = Caml_option.valFromOption(meta);
          }
          if (suspense !== undefined) {
            tmp.suspense = Caml_option.valFromOption(suspense);
          }
          if (preferGetMethod !== undefined) {
            tmp.preferGetMethod = Caml_option.valFromOption(preferGetMethod);
          }
          return tmp;
        }), [
        additionalTypenames,
        fetchOptions,
        $$fetch,
        url,
        rp,
        meta,
        suspense,
        preferGetMethod
      ]);
  var args = React.useMemo((function (param) {
          return {
                  query: query,
                  variables: Curry._1(Subscription.variablesToJson, Curry._1(Subscription.serializeVariables, variables)),
                  pause: pause,
                  context: context
                };
        }), [
        query,
        variables,
        pause,
        context
      ]);
  var h = function (acc, subscriptionResult) {
    if (typeof handler !== "object") {
      return Curry._1(parse, subscriptionResult);
    } else {
      return Curry._2(handler._0, acc, Curry._1(parse, subscriptionResult));
    }
  };
  var match = Urql.useSubscription(args, h);
  var executeSubscriptionJs = match[1];
  var responseJs = match[0];
  var state = React.useMemo((function (param) {
          var error = responseJs.error;
          var fetching = responseJs.fetching;
          var data = responseJs.data;
          var response;
          var exit = 0;
          if (fetching) {
            if ((data == null) && error === undefined) {
              response = "Fetching";
            } else {
              exit = 1;
            }
          } else if ((data == null) && error === undefined) {
            response = "Empty";
          } else {
            exit = 1;
          }
          if (exit === 1) {
            response = (data == null) ? ({
                  TAG: "Error",
                  _0: error
                }) : (
                error !== undefined ? ({
                      TAG: "PartialData",
                      _0: data,
                      _1: error.graphQLErrors
                    }) : ({
                      TAG: "Data",
                      _0: data
                    })
              );
          }
          return {
                  operation: responseJs.operation,
                  fetching: fetching,
                  data: (data == null) ? undefined : Caml_option.some(data),
                  error: error,
                  response: response,
                  extensions: responseJs.extensions,
                  stale: responseJs.stale
                };
        }), [responseJs]);
  var executeSubscription = React.useMemo((function (param) {
          return function (additionalTypenames, fetchOptions, $$fetch, requestPolicy, url, meta, suspense, preferGetMethod, param) {
            var tmp = {};
            if (additionalTypenames !== undefined) {
              tmp.additionalTypenames = Caml_option.valFromOption(additionalTypenames);
            }
            if ($$fetch !== undefined) {
              tmp.fetch = Caml_option.valFromOption($$fetch);
            }
            if (fetchOptions !== undefined) {
              tmp.fetchOptions = Caml_option.valFromOption(fetchOptions);
            }
            var tmp$1 = Belt_Option.map(requestPolicy, Types$ReScriptUrql.requestPolicyToJs);
            if (tmp$1 !== undefined) {
              tmp.requestPolicy = Caml_option.valFromOption(tmp$1);
            }
            if (url !== undefined) {
              tmp.url = Caml_option.valFromOption(url);
            }
            if (meta !== undefined) {
              tmp.meta = Caml_option.valFromOption(meta);
            }
            if (suspense !== undefined) {
              tmp.suspense = Caml_option.valFromOption(suspense);
            }
            if (preferGetMethod !== undefined) {
              tmp.preferGetMethod = Caml_option.valFromOption(preferGetMethod);
            }
            return Curry._1(executeSubscriptionJs, tmp);
          };
        }), [executeSubscriptionJs]);
  return [
          state,
          executeSubscription
        ];
}

export {
  useSubscription ,
}
/* urql Not a pure module */
