// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Urql = require("urql");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Header$ReactTemplate = require("./Header.bs.js");
var DogList$ReactTemplate = require("./DogList.bs.js");
var Provider$ReactTemplate = require("../../src/Provider.bs.js");

var config = {
  url: "http://localhost:3001"
};

var client = new Urql.Client(config);

var component = ReasonReact.statelessComponent("App");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(/* None */0, /* None */0, Provider$ReactTemplate.make(client, /* array */[
                              ReasonReact.element(/* None */0, /* None */0, Header$ReactTemplate.make(/* array */[])),
                              ReasonReact.element(/* None */0, /* None */0, DogList$ReactTemplate.make(/* array */[]))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.config = config;
exports.client = client;
exports.component = component;
exports.make = make;
/* client Not a pure module */
