// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Dog");

function make(description, id, imageUrl, name, likes, onClick, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          style: {
                            fontFamily: "Space Mono",
                            padding: "10px"
                          },
                          onClick: (function () {
                              return Curry._1(onClick, {
                                          key: id
                                        });
                            })
                        }, React.createElement("img", {
                              style: {
                                maxHeight: "200px"
                              },
                              alt: name,
                              src: imageUrl
                            }), React.createElement("div", {
                              style: {
                                borderBottom: "1px solid #222",
                                color: "#222",
                                display: "flex",
                                fontSize: "20px",
                                fontWeight: "700",
                                marginBottom: "5px",
                                justifyContent: "space-between"
                              }
                            }, React.createElement("span", undefined, name), React.createElement("span", undefined, "" + (String(likes) + " likes"))), React.createElement("div", undefined, description));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
