// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Urql = require("urql");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var App$ReactTemplate = require("./App.bs.js");

var query = Urql.query("\nquery {\n  dogs {\n    name\n    breed\n    description\n  }\n}\n", undefined);

var fetchOptions = {
  formidable: 1
};

function fetchFunc_001() {
  return {
          formidable: 5000
        };
}

var fetchFunc = /* `FetchFunc */[
  1011003518,
  fetchFunc_001
];

var config = {
  url: "http://localhost:3001",
  fetchOptions: /* `FetchObj */[
    852414461,
    fetchOptions
  ]
};

var client = new Urql.Client(config);

client.executeQuery(query, false).then((function (value) {
        var dogs = value.data.dogs;
        console.log(dogs);
        return Promise.resolve(dogs);
      }));

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$ReactTemplate.make(/* array */[])), "root");

exports.query = query;
exports.fetchOptions = fetchOptions;
exports.fetchFunc = fetchFunc;
exports.config = config;
exports.client = client;
/* query Not a pure module */
