// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Urql = require("urql");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Connect$ReactTemplate = require("../../src/Connect.bs.js");

var component = ReasonReact.statelessComponent("Header");

var likeAllDogs = Urql.mutation("\n    mutation likeAllDogs {\n      likeAllDogs {\n        key\n        likes\n      }\n    }\n  ", undefined);

var mutationMap = { };

mutationMap["likeAllDogs"] = likeAllDogs;

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(/* None */0, /* None */0, Connect$ReactTemplate.make(/* None */0, /* Some */[mutationMap], (function (result) {
                                return React.createElement("header", {
                                            style: {
                                              background: "#a1a1a1",
                                              display: "flex",
                                              fontFamily: "Space Mono",
                                              minHeight: "15%",
                                              padding: "10px",
                                              alignItems: "center"
                                            }
                                          }, React.createElement("img", {
                                                src: "../../assets/formidable-logo.svg",
                                                onClick: (function () {
                                                    result.likeAllDogs();
                                                    return /* () */0;
                                                  })
                                              }), React.createElement("span", {
                                                style: {
                                                  fontSize: "25px",
                                                  marginLeft: "10px"
                                                }
                                              }, "Dogs"));
                              }), /* None */0, /* None */0, /* None */0, /* array */[]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.mutationMap = mutationMap;
exports.make = make;
/* component Not a pure module */
