// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Urql = require("urql");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function unwrapQuery(q) {
  if (q) {
    return q[0][1];
  } else {
    return "";
  }
}

function unwrapMutation(m) {
  if (m) {
    return m[0];
  } else {
    return { };
  }
}

var component = ReasonReact.statelessComponent("Connect");

function make(query, mutation, renderProp, $staropt$star, $staropt$star$1, shouldInvalidate, _children) {
  var cache = $staropt$star ? $staropt$star[0] : true;
  var typeInvalidation = $staropt$star$1 ? $staropt$star$1[0] : true;
  return ReasonReact.wrapJsForReason(Urql.Connect, {
              query: unwrapQuery(query),
              mutation: unwrapMutation(mutation),
              cache: cache,
              typeInvalidation: typeInvalidation,
              shouldInvalidate: shouldInvalidate,
              children: renderProp
            }, _children);
}

exports.unwrapQuery = unwrapQuery;
exports.unwrapMutation = unwrapMutation;
exports.component = component;
exports.make = make;
/* component Not a pure module */
