// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Urql = require("urql");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Provider");

function make(client, children) {
  return ReasonReact.wrapJsForReason(Urql.Provider, {
              client: client
            }, children);
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
