// Generated by ReScript, PLEASE EDIT WITH CARE


var Source = {};

var Consumer = {};

var Subscription = {
  Consumer: Consumer
};

var Signal = {};

var Operator = {};

var Sink = {};

export {
  Source ,
  Subscription ,
  Signal ,
  Operator ,
  Sink ,
}
/* No side effect */
